const express=require("express");
const {  authcontroller } = require("./auth.controller");
const authRouter=express.Router();
authRouter.post("/register",authcontroller.registerController);
authRouter.post("/register",authcontroller.loginController);
authRouter.post("/register",authcontroller.logoutController);
authRouter.post("/register",authcontroller.meController);
authRouter.post("/register",authcontroller.refreshController);
authRouter.post("/register",authcontroller.changeController);
module.exports=authRouter;
