const express=require("express");
const {  authcontroller } = require("./auth.controller");
const authRouter=express.Router();
authRouter.post("/register",authcontroller.registerController);
authRouter.post("/login",authcontroller.loginController);
authRouter.post("/logout",authcontroller.logoutController);
authRouter.post("/me",authcontroller.meController);
authRouter.post("/refresh",authcontroller.refreshController);
authRouter.post("/change",authcontroller.changeController);
module.exports=authRouter;
